TEMPLATES_DIR = 'templates'
TEMPLATE_FILE_NAME = 'index.html'
POSTMAN_JSON_SCHEMA = 'schema_2_1_0.json'
POSTMAN_SCHEMA_DIR = 'schemas'
OUTPUT_DIR = 'output'
OUTPUT_FILE_NAME = 'index.html'

CSS_DIR = 'css'
JS_DIR = 'js'

FOLDER_ICON = 'fas fa-folder'

INFO = 'info'
SCHEMA = 'schema'
NAME = 'name'
REQUEST = 'request'
METHOD = 'method'
DESCRIPTION = 'description'
URL = 'url'
MODE = 'mode'
RAW = 'raw'
URL_ENCODED = 'urlencoded'
FORM_DATA='formdata'
RESPONSE = 'response'
ORIGINAL_REQUEST = 'originalRequest'
STATUS = 'status'
CODE = 'code'
BODY = 'body'
KEY = 'key'
VALUE = 'value'
HEADER = 'header'
QUERY = 'query'
PATH_VARIABLE = 'variable'
CONTENT = 'content'
NOT_FOUND ='[NOT FOUND]'


